{
  "formatVersion": "1.1",
  "component": {
    "group": "com.perf.plugin",
    "module": "myplugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myplugin-1.0.0.jar",
          "url": "myplugin-1.0.0.jar",
          "size": 17057,
          "sha512": "6813ed6cdf4065698a72984b194a4cf84964d9644eb80f7bdcd75218c83b6955eac0d2f3885f4ce562e737ef74103726913f707594c31e15dd124da265a09212",
          "sha256": "b601710b78359fa7327015c2415a80769f46d876a373d70eb88e0c124cf77155",
          "sha1": "2fd751fed5074c070b673c62ba77f9ff809a1f8f",
          "md5": "286cedbba4a783d7776ee8b2213aba28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.1"
          }
        }
      ],
      "files": [
        {
          "name": "myplugin-1.0.0.jar",
          "url": "myplugin-1.0.0.jar",
          "size": 17057,
          "sha512": "6813ed6cdf4065698a72984b194a4cf84964d9644eb80f7bdcd75218c83b6955eac0d2f3885f4ce562e737ef74103726913f707594c31e15dd124da265a09212",
          "sha256": "b601710b78359fa7327015c2415a80769f46d876a373d70eb88e0c124cf77155",
          "sha1": "2fd751fed5074c070b673c62ba77f9ff809a1f8f",
          "md5": "286cedbba4a783d7776ee8b2213aba28"
        }
      ]
    }
  ]
}
